### ISSUE TITLE
后台实现

### ISSUE THREAD

**Issue by ibertli** [Zealon159/book-ms-ui#1]
请问一下后台是怎么收到前端修改请求呢？数据需要数据库吗？

**Comment by Zealon159** [comment]
> 请问一下后台是怎么收到前端修改请求呢？数据需要数据库吗？

对呀，后台有专门的接口项目，用的java语言开发的，springboot技术栈，数据都要持久化到MySQL中，后台项目仓库是 https://github.com/zealon159/book-ms-interface ，里面有详细介绍和建库脚本。
